[book]
authors = ["Kai Li"]
language = "en"
multilingual = false
src = "src"
title = "Hungry"

[output.html]
mathjax-support = true
additional-js = ["theme/reading-position.js"]
additional-css = ["theme/novel.css"]
